### ISSUE TITLE
Cool website!

### ISSUE THREAD

**Issue by RichardLitt** [rhine3/goldeneye#4]
Just saw http://alphacodes.net/. Great work. :) Mind if I share it around?

**Comment by rhine3** [comment]
Thanks Richard! Sorry, somehow I didn't see this until now -- please feel free to share!

**Comment by RichardLitt** [comment]
No worries! Not sure what I meant by "share it around", but I guess I wanted to say thanks! Thanks!

**Comment by rhine3** [comment]
You're welcome! So glad you're finding it useful :)
